
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pavanreddy
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

#  main:
#    web-application-type: reactive
server:
  port: 9191

#logging:
#  level:
#    org:
#      hibernate:
#        sql: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder=TRACE:

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
